alias bx="bundle exec"
alias cuke="bundle exec cucumber"
alias spek="bundle exec rspec"
alias rakk="bundle exec rake"
alias con="bundle exec script/console"
alias cdb="cd /Developer/betterplace"
alias cdc="cd /Developer/provisioning/chef-repo"
alias cdm="cd /Developer/bettermobile"