alias bx="bundle exec"
alias spek="spring rspec"
alias rakk="spring rake"
alias cdb="cd /Developer/betterplace"
alias cdc="cd /Developer/provisioning/chef-repo"
alias cda="cd /Developer/provisioning/betterplace-provisioning"
alias cde="cd /Developer/epo"
