#!/usr/bin/env bash
#
# Run all dotfiles installers. Safe to run at any time to update.

set -e

cd "$(dirname "$0")"/..

HOSTNAME=$(scutil --get LocalHostName)

echo "› darwin-rebuild switch"
sudo darwin-rebuild switch --flake /Users/daniel/.dotfiles/nix#${HOSTNAME}

# Run any remaining install.sh scripts (legacy)
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
